---

- name: CentOS | Upgrade all packages
  yum: name=* state=latest

- name: Install yum-cron
  package: name=yum-cron state=present

- name: Enabling yum-cron on boot
  service: name=yum-cron state=started enabled=yes

- name: Securing SSH configuration
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PermitRootLogin"
    line: "PermitRootLogin without-password"
    state: present
  notify: restart sshd

- name: remove unused repositories
  file:
    name: '/etc/yum.repos.d/{{ item }}.repo'
    state: 'absent'
  with_items:
    - 'CentOS-Debuginfo'
    - 'CentOS-Media'
    - 'CentOS-Vault'